AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: sam-test

Globals:
  Function:
    Runtime: nodejs12.x
    MemorySize: 128
    Timeout: 29
    Environment:
        Variables:
          SAMPLE_TABLE: !Ref SampleTable

Resources:
  getAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Get all items from a DynamoDB table.
      Handler: src/handlers/get-all-items.getAllItemsHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET

  getByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Get one item by id from a DynamoDB table.
      Handler: src/handlers/get-by-id.getByIdHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{id}
            Method: GET

  putItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Add one item to a DynamoDB table.
      Handler: src/handlers/put-item.putItemHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST

  SampleTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
