AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.handler
      Runtime: nodejs12.x
      Timeout: 29
      # FunctionName: GetDocumentFunction
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /email
            Method: GET

      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt HelloWorldTopic.TopicName

      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref HelloWorldTopic
          
  HelloWorldTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: xxxx@gmail.com
          Protocol: email